package org.openthinclient.web.pkgmngr.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PackageListMasterDetailsDesign extends VerticalLayout {
  protected HorizontalSplitPanel splitPanel;
  protected CssLayout sourceUpdatePanel;
  protected Label sourceUpdateLabel;
  protected Button sourceUpdateButton;
  protected CheckBox packageFilerCheckbox;
  protected Button searchButton;
  protected TextField searchTextField;
  protected Grid<org.openthinclient.web.pkgmngr.ui.view.AbstractPackageItem> packageList;
  protected VerticalLayout detailsContainer;

  public PackageListMasterDetailsDesign() {
    Design.read(this);
  }
}
