package org.openthinclient.web.pkgmngr.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import org.openthinclient.web.pkgmngr.ui.view.AbstractPackageItem;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PackageDetailsDesign extends VerticalLayout {
  protected Label name;
  protected Label version;
  protected Label shortDescription;
  protected Label description;
  protected Grid<AbstractPackageItem> dependencies;
  protected Grid<AbstractPackageItem> conflicts;
  protected Label conflictsLabel;
  protected Grid<AbstractPackageItem> provides;
  protected Label providesLabel;
  protected Label sourceUrl;
  protected Label changeLog;

  public PackageDetailsDesign() {
    Design.read(this);
  }
}
