package org.openthinclient.web.pkgmngr.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView
 * extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PackageActionOverviewDesign extends VerticalLayout {
  protected Label labelCaption;
  protected Label descriptionLabel;
  protected Grid<org.openthinclient.web.pkgmngr.ui.view.ResolvedPackageItem> packageSelectionGrid;
  protected HorizontalLayout actionBar;
  protected Button performActionButton;

  public PackageActionOverviewDesign() {
    Design.read(this);
  }
}
