package org.openthinclient.web.pkgmngr.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SourcesListDesign extends VerticalLayout {
	protected Table sourcesTable;
	protected Button updateButton;
	protected Button addSourceButton;
	protected Button deleteSourceButton;
	protected TextField urlText;
	protected CheckBox enabledCheckbox;
	protected TextArea descriptionTextArea;
	protected Button saveButton;

	public SourcesListDesign() {
		Design.read(this);
	}
}
