package org.openthinclient.web.pkgmngr.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SourcesListDesign extends VerticalLayout {
	protected Table sourcesTable;
	protected Button updateButton;
	protected Button addSourceButton;
	protected Button deleteSourceButton;
	protected TextField urlText;
	protected CheckBox enabledCheckbox;
	protected TextArea descriptionTextArea;
	protected Button saveButton;
	protected Button updateButtonTop;
	protected Label sourceDetailsLabel;
	protected Label sourcesLabel;
	protected HorizontalLayout sourcesLayout;
	protected VerticalLayout sourceDetailsLayout;

	public SourcesListDesign() {
		Design.read(this);
	}
}
