/*******************************************************************************
 * openthinclient.org ThinClient suite
 * 
 * Copyright (C) 2004, 2007 levigo holding GmbH. All Rights Reserved.
 * 
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place - Suite 330, Boston, MA 02111-1307, USA.
 *******************************************************************************/
/*
 * Automatically generated by jrpcgen 1.0.5 on 29.04.05 21:09 jrpcgen is part of
 * the "Remote Tea" ONC/RPC package for Java See
 * http://remotetea.sourceforge.net for details
 */
package org.openthinclient.nfsd.tea;

/**
 * Enumeration (collection of constants).
 */
public interface nfsstat {

  public static final int NFS_OK = 0;
  public static final int NFSERR_PERM = 1;
  public static final int NFSERR_NOENT = 2;
  public static final int NFSERR_IO = 5;
  public static final int NFSERR_NXIO = 6;
  public static final int NFSERR_ACCES = 13;
  public static final int NFSERR_EXIST = 17;
  public static final int NFSERR_NODEV = 19;
  public static final int NFSERR_NOTDIR = 20;
  public static final int NFSERR_ISDIR = 21;
  public static final int NFSERR_FBIG = 27;
  public static final int NFSERR_NOSPC = 28;
  public static final int NFSERR_ROFS = 30;
  public static final int NFSERR_NAMETOOLONG = 63;
  public static final int NFSERR_NOTEMPTY = 66;
  public static final int NFSERR_DQUOT = 69;
  public static final int NFSERR_STALE = 70;
  public static final int NFSERR_WFLUSH = 99;

}
// End of nfsstat.java
